### ISSUE TITLE
Double Scroll Bar

### ISSUE THREAD

**Issue by homotechsual** [christian-bromann/docusaurus-theme-github-codeblock#12]
Hi Christian - thanks for forking this - the improvements look great!

I'm seeing a double vertical scroll bar caused by the repetition of the `language-*` class on the immediate child of `docusaurus-theme-github-codeblock` and the child of `codeBlockContent` which is where it should be (alongside `prism-code`).

Not sure the best fix here - ideally not putting the class on the parent element but otherwise this CSS resolves:

```css
/* GitHub Code Block */

// Fix for doubled up `language-*` class causing a double scroll bar effect.

.docusaurus-theme-github-codeblock > [class*="language-"] {
  max-height: none;
}
```
